const assert = require('node:assert/strict')
const { spawnSync } = require('node:child_process')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { test } = require('node:test')
const { stageUpdateTools } = require('../build-config/portable-update.cjs')
const load = require('./helpers/load-typescript.cjs')
const { safeRemove } = require('./helpers/windows-update-fixture.cjs')
const api = load({ '@common/utils/undiciCompat': {} })('src/main/modules/winMain/updatePortable.ts')
const runtime = { edition: 'portable', arch: 'x64', win7: false }

test('the packaged extractor stages the complete green archive and rejects user-data contents', { skip: process.platform !== 'win32', timeout: 30000 }, async(t) => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'lx-archive-update-'))
  t.after(() => safeRemove(root, 'lx-archive-update-'))
  const current = path.join(root, 'old')
  const next = path.join(root, 'next')
  fs.mkdirSync(current)
  fs.mkdirSync(path.join(next, 'resources'), { recursive: true })
  const pe = Buffer.alloc(256)
  pe.write('MZ'); pe.writeUInt32LE(128, 60); pe.writeUInt32LE(0x4550, 128); pe.writeUInt16LE(0x8664, 132)
  fs.writeFileSync(path.join(next, 'LX-M Music.exe'), pe)
  fs.writeFileSync(path.join(next, 'resources/app.asar'), 'new app contents')
  fs.writeFileSync(path.join(next, 'resources/lx-update-runtime.json'), JSON.stringify({ schema: 1, appId: 'com.lx-m.music.desktop', edition: 'portable', arch: 'x64', win7: false, version: '9.0.0' }))
  await stageUpdateTools(current)
  const sevenZip = path.join(current, 'resources/update-tools/7za.exe')
  assert(fs.existsSync(sevenZip))
  const archive = path.join(root, 'green.7z')
  const pack = () => {
    const result = spawnSync(sevenZip, ['a', '-t7z', '-mx=1', archive, '.'], { cwd: next, windowsHide: true, encoding: 'utf8' })
    assert.equal(result.status, 0, result.stdout + result.stderr)
  }
  pack()
  const executable = path.join(current, 'my renamed app.exe')
  const stage = await api.prepareArchiveUpdate(archive, path.join(root, 'good-stage'), executable, path.join(current, 'resources'), new AbortController().signal)
  assert(stage.files.some(file => file.path === 'my renamed app.exe' && file.source === 'LX-M Music.exe'))
  assert.equal(fs.readFileSync(path.join(stage.directory, 'resources/app.asar'), 'utf8'), 'new app contents')
  await api.validateStagedPortable(stage, runtime, '9.0.0')
  await assert.rejects(api.validateStagedPortable(stage, { ...runtime, arch: 'arm64' }, '9.0.0'), /不匹配/)
  fs.mkdirSync(path.join(next, 'portable/userData'), { recursive: true })
  fs.writeFileSync(path.join(next, 'portable/userData/music.db'), 'should never overwrite local data')
  fs.unlinkSync(archive)
  pack()
  const rejectedStage = path.join(root, 'bad-stage')
  await assert.rejects(api.prepareArchiveUpdate(archive, rejectedStage, executable, path.join(current, 'resources'), new AbortController().signal), /非程序文件/)
  assert(!fs.existsSync(rejectedStage), 'unsafe entries must be rejected before extraction')
})
